# Generated by Django 3.1.3 on 2021-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('char', models.CharField(max_length=255)),
            ],
        ),
    ]
